FROM almalinux:8

ADD hello.txt /tmp/ 
ADD https://raw.githubusercontent.com/sivadevopsdaws74s/dockerfiles/master/commands.MD /tmp/
ADD https://raw.githubusercontent.com/sivadevopsdaws74s/roboshop-documentation/refs/heads/master/01-web.MD /tmp/
ADD sample-1.tar /tmp/